# Generated by Django 4.2.3 on 2023-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('upvote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_name', models.CharField(max_length=12)),
                ('score_num', models.IntegerField(default=0)),
                ('score_time', models.TimeField(default=0)),
            ],
        ),
    ]
